spring:
  jmx:
    enabled: true
  profiles:
    active: local  # 로컬 개발 시 application-local.yaml 병합
  config:
    import: classpath:filter-pipeline.yaml

  datasource:
    url: jdbc:postgresql://localhost:5433/postgres
    username: postgres
    password:  # application-local.yaml 에서 설정

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        '[format_sql]': true

  ai:
    ollama:
      base-url: http://localhost:11434
      chat:
        options:
          model: llama3
          temperature: 0.1
      embedding:
        options:
          model: bge-m3

    vectorstore:
      pgvector:
        table-name: bad_word_vectors
        dimensions: 1024
        initialize-schema: false
        index-type: HNSW
        distance-type: COSINE_DISTANCE

logging:
  level:
    '[com.lily.spring_ai_vector]': INFO
    '[org.springframework.ai.chat.client.advisor]': DEBUG
